### ISSUE TITLE
Trying to install the package from atom gives an error

### ISSUE THREAD

**Issue by pepite** [k33g/language-golo#3]
Installing the package from atom gives the following output:

```
Unable to download https://www.atom.io/api/packages/language-golo/versions/0.8.0/tarball: 400 Bad Request Repository inaccessible
```

**Comment by k33g** [comment]
ok, I think it's because I moved this repository from my own repository to this repository

**Comment by k33g** [comment]
@pepite moved again to original github user
package install is ok again

**Comment by pepite** [comment]
Thanks :)

**Comment by k33g** [comment]
I need to update it with the new Golo features
